arm_joint_1_position:
  type: effort_controllers/JointPositionController
  joint: arm_joint_1
  pid: &joint_pid {p: 100.0, d: 0.1, i: 1.0, i_clamp: 1.0}

arm_joint_2_position:
  type: effort_controllers/JointPositionController
  joint: arm_joint_2
  pid: *joint_pid

arm_joint_3_position:
  type: effort_controllers/JointPositionController
  joint: arm_joint_3
  pid: *joint_pid

arm_joint_4_position:
  type: effort_controllers/JointPositionController
  joint: arm_joint_4
  pid: *joint_pid
