arm_joint_1_effort:
  type: effort_controllers/JointEffortController
  joint: arm_joint_1

arm_joint_2_effort:
  type: effort_controllers/JointEffortController
  joint: arm_joint_2

arm_joint_3_effort:
  type: effort_controllers/JointEffortController
  joint: arm_joint_3

arm_joint_4_effort:
  type: effort_controllers/JointEffortController
  joint: arm_joint_4
