<?xml version="1.0"?>

<robot
  xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller" 
  xmlns:interface="http://ros.org/wiki/xacro" 
  xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor" 
  xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:include filename="$(find tuda_turtlebot3_description)/urdf/common_properties.xacro" />
  <xacro:include filename="$(find tuda_turtlebot3_description)/urdf/tuda_turtlebot3.gazebo.xacro" />
  <xacro:include filename="$(find tuda_turtlebot3_camera_description)/urdf/logitech_c930e.urdf.xacro" />
  <xacro:include filename="$(find hector_xacro_tools)/urdf/inertia_tensors.urdf.xacro" />

  <xacro:property name="XL430_W250_max_effort" value="1.5" />
  <xacro:property name="XL430_W250_max_velocity" value="${61 * 2*pi/60}" />

  <xacro:property name="wheel_joint_damping" value="0.5" />
  <xacro:property name="wheel_joint_friction" value="1.0" />
  
  <xacro:property name="collision_cylinder_x_offset" value="-0.022"/>
  <xacro:property name="collision_cylinder_y_offset" value="0.042"/>
  <xacro:property name="collision_cylinder_radius" value="0.003"/>

  <xacro:macro name="turtlebot3_macro" params="with_arm">
    <link name="base_footprint" />

    <joint name="base_joint" type="fixed">
      <parent link="base_footprint" />
      <child link="base_link" />
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
    </joint>

    <link name="base_link">
      <visual>
        <origin xyz="0.032 0.0 0.0" rpy="0.0 0.0 ${pi}" />
        <geometry>
          <mesh filename="package://tuda_turtlebot3_description/meshes/base/tuda_turtlebot3_base.stl" scale="0.001 0.001 0.001" />
        </geometry>
        <material name="light_black" />
      </visual>

      <collision>
        <origin xyz="0.032 0.0 0.0465" rpy="0.0 0.0 ${pi}" />
        <geometry>
          <box size="0.13755 0.140 0.093" />
        </geometry>
      </collision>

<!--      <collision>
        <origin xyz="0.032 0.0 0.119" rpy="0.0 0.0 ${pi}" />
        <geometry>
          <box size="0.13755 0.092 0.052" />
        </geometry>
      </collision>-->
      
      <!-- Top plate -->
      <collision>
        <origin xyz="0.032 0.0 0.14" rpy="0.0 0.0 ${pi}" />
        <geometry>
          <box size="0.13755 0.092 0.01" />
        </geometry>
      </collision>
      
      <!-- top of platform is at 0.093 -->
      <!-- bottom of top plate is at 0.135-->
      
      <!-- Cylinders -->
      <collision>
        <origin xyz="${0.032 + collision_cylinder_x_offset} ${collision_cylinder_y_offset} 0.114" rpy="0.0 0.0 ${pi}" />
        <geometry>
          <cylinder length="0.042" radius="${collision_cylinder_radius}"/>
        </geometry>
      </collision>
      <collision>
        <origin xyz="${0.032 + collision_cylinder_x_offset} ${-collision_cylinder_y_offset-0.001} 0.114" rpy="0.0 0.0 ${pi}" />
        <geometry>
          <cylinder length="0.042" radius="${collision_cylinder_radius}"/>
        </geometry>
      </collision>
      
      
      <collision>
        <origin xyz="0.133 0.0 0.025" rpy="0.0 0.0 ${pi}" />
        <geometry>
          <box size="0.068 0.140 0.05" />
        </geometry>
      </collision>

      <collision>
        <origin xyz="0.17407 0.0 0.013" rpy="0.0 0.0 0.0" />
        <geometry>
          <box size="0.0145 0.140 0.026" />
        </geometry>
      </collision>

      <inertial>
        <origin xyz="0.0 0.00062 0.01577" rpy="0.0 0.0 ${pi}" />
        <mass value="1.265" />
        <inertia ixx="3316.323e-06" ixy="-116.278e-06" ixz="406.012e-06"
                 iyy="4901.926e-06" iyz="28.730e-06"
                 izz="4991.998e-06" />
      </inertial>
    </link>

    <joint name="wheel_left_joint" type="continuous">
      <parent link="base_link" />
      <child link="wheel_left_link" />
      <origin xyz="0.0 0.08 0.02325" rpy="${pi*0.5} 0 ${pi}" />
      <axis xyz="0 0 1" />
      <limit effort="${XL430_W250_max_effort}" velocity="${XL430_W250_max_velocity}" />
      <joint_properties damping="${wheel_joint_damping}" friction="{wheel_joint_friction}" />
    </joint>

    <link name="wheel_left_link">
      <visual>
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://tuda_turtlebot3_description/meshes/wheels/tire_on_wheel.stl" scale="0.001 0.001 0.001" />
        </geometry>
        <material name="dark" />
      </visual>

      <collision>
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
        <geometry>
          <cylinder length="0.018" radius="0.033" />
        </geometry>
      </collision>

      <inertial>
        <origin xyz="0.0 0.0 0.0" />
        <mass value="0.061" />
        <inertia ixx="21.298e-06" ixy="-0.007e-06" ixz="-0.003e-06"
                 iyy="21.289e-06" iyz="0.006e-06"
                 izz="39.702e-06" />
      </inertial>
    </link>

    <joint name="wheel_right_joint" type="continuous">
      <parent link="base_link" />
      <child link="wheel_right_link" />
      <origin xyz="0.0 -0.08 0.02325" rpy="${pi*0.5} 0 ${pi}" />
      <axis xyz="0 0 1" />
      <limit effort="${XL430_W250_max_effort}" velocity="${XL430_W250_max_velocity}" />
      <joint_properties damping="${wheel_joint_damping}" friction="{wheel_joint_friction}" />
    </joint>

    <link name="wheel_right_link">
      <visual>
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://tuda_turtlebot3_description/meshes/wheels/tire_on_wheel.stl" scale="0.001 0.001 -0.001" />
        </geometry>
        <material name="dark" />
      </visual>

      <collision>
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
        <geometry>
          <cylinder length="0.018" radius="0.033" />
        </geometry>
      </collision>

      <inertial>
        <origin xyz="0.0 0.0 0.0" />
        <mass value="0.061" />
        <inertia ixx="21.302e-06" ixy="0.002e-06" ixz="0.0"
                 iyy="21.286e-06" iyz="0.006e-06"
                 izz="39.702e-06" />
      </inertial>
    </link>

    <joint name="caster_front_left_joint" type="fixed">
      <parent link="base_link" />
      <child link="caster_front_left_link" />
      <origin xyz="0.144 0.052 -0.006" rpy="0.0 0.0 0.0" />
    </joint>

    <link name="caster_front_left_link">
      <visual>
        <origin xyz="0.0 0.0 0.0065" rpy="0.0 0.0 0.0" />
        <geometry>
          <mesh filename="package://tuda_turtlebot3_description/meshes/base/ball_caster.stl" scale="0.001 0.001 0.001" />
        </geometry>
        <material name="light_black" />
      </visual>
	  
      <collision>
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
        <geometry>
          <sphere radius="0.004"/>
        </geometry>
      </collision>

      <inertial>
        <origin xyz="0.001 0 0.00073" />
        <mass value="0.004" />
        <inertia ixx="0.115e-06" ixy="0.0" ixz="0.0"
                 iyy="0.274e-06" iyz="0.0"
                 izz="0.206e-06" />
      </inertial>
    </link>
	
    <joint name="caster_front_right_joint" type="fixed">
      <parent link="base_link" />
      <child link="caster_front_right_link" />
      <origin xyz="0.144 -0.052 -0.006" rpy="0.0 0.0 0.0" />
    </joint>

    <link name="caster_front_right_link">
	  <visual>
        <origin xyz="0.0 0.0 0.0065" rpy="0.0 0.0 0.0" />
        <geometry>
          <mesh filename="package://tuda_turtlebot3_description/meshes/base/ball_caster.stl" scale="0.001 0.001 0.001" />
        </geometry>
        <material name="light_black" />
      </visual>
	  
      <collision>
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
        <geometry>
          <sphere radius="0.004"/>
        </geometry>
      </collision>

      <inertial>
        <origin xyz="0.001 0 0.00073" />
        <mass value="0.004" />
        <inertia ixx="0.115e-06" ixy="0.0" ixz="0.0"
                 iyy="0.274e-06" iyz="0.0"
                 izz="0.206e-06" />
      </inertial>
    </link>
	
	<joint name="usb_mount_joint" type="fixed">
      <parent link="base_link" />
      <child link="usb_mount_link" />
      <origin xyz="0.127 0.024 0.04875" rpy="0.0 0.0 ${pi}" />
    </joint>

    <link name="usb_mount_link">
	  <visual>
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
        <geometry>
          <mesh filename="package://tuda_turtlebot3_description/meshes/base/usb_mount.stl" scale="0.001 0.001 0.001" />
        </geometry>
        <material name="light_black" />
      </visual>
	  
      <collision>
        <origin xyz="0.031 -0.020 -0.006" rpy="0.0 0.0 0.0" />
        <geometry>
          <box size="0.062 0.040 0.012" />
        </geometry>
      </collision>
	  
      <collision>
        <origin xyz="0.031 -0.02904 0.025" rpy="0.0 0.0 0.0" />
        <geometry>
          <box size="0.021 0.015 0.050" />
        </geometry>
      </collision>
	  
      <collision>
        <origin xyz="0.031 -0.02904 -0.011" rpy="0.0 0.0 0.0" />
        <geometry>
          <box size="0.021 0.01921 0.022" />
        </geometry>
      </collision>

      <inertial>
        <origin xyz="0.001 0 0.00073" />
        <mass value="0.005" />
        <inertia ixx="0.1e-06" ixy="0.0" ixz="0.0"
                 iyy="0.1e-06" iyz="0.0"
                 izz="0.1e-06" />
      </inertial>
    </link>

    <!-- TurtleBot3 Sensors-->
    <joint name="imu_joint" type="fixed">
      <parent link="base_link" />
      <child link="imu_link" />
      <origin xyz="0.0265 0.007 0.058" rpy="0.0 0.0 0.0" />
    </joint>

    <link name="imu_link">
      <inertial>
        <origin xyz="0.0 0.0 0.0" />
        <mass value="0.01" />
        <inertia ixx="0.001" ixy="0.0" ixz="0.0"
                 iyy="0.001" iyz="0.0"
                 izz="0.001" />
      </inertial>
    </link>

    <joint name="scan_joint" type="fixed">
      <parent link="base_link" />
      <child link="base_scan" />
      <origin xyz="0.02076 0 0.1225" rpy="0.0 0.0 0.0" />
    </joint>

    <link name="base_scan">
      <visual>
        <origin xyz="0.0 0.0 -0.01" rpy="0.0 0.0 ${pi}" />
        <geometry>
          <mesh filename="package://tuda_turtlebot3_description/meshes/sensors/lds.stl" scale="0.001 0.001 0.001" />
        </geometry>
        <material name="dark" />
      </visual>

      <collision>
        <origin xyz="0.012 0.0 -0.01" rpy="0.0 0.0 0.0" />
        <geometry>
          <cylinder length="0.040" radius="0.03" />
        </geometry>
      </collision>

      <inertial>
        <mass value="0.125" />
        <origin xyz="-0.00687 0.0001 0.0038" />
        <inertia ixx="-1.801e-06" ixy="-0.007e-06" ixz="3.231e-06"
                 iyy="-7.595e-06" iyz="0.004e-06"
                 izz="-5.794e-06" />
      </inertial>
    </link>
	
    <!-- camera -->
	  <joint name="logitech_mount_joint" type="fixed">
      <parent link="base_link" />
      <child link="camera_mount_link" />
      <origin xyz="0.164 0.0 0.033" rpy="0.0 0.0 0.0" />
    </joint>
	
	  <link name="camera_mount_link">
      <visual>
        <origin xyz="0.0 0.0 0.0" rpy="${-pi/2} 0.0 ${-pi/2}" />
        <geometry>
          <mesh filename="package://tuda_turtlebot3_camera_description/meshes/c930_mount.stl" scale="0.001 0.001 0.001" />
        </geometry>
        <material name="dark" />
      </visual>

      <collision>
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
        <geometry>
          <box size="0.048 0.054 0.032" />
        </geometry>
      </collision>

      <!--inertial>
        <mass value="0.0" />
        <origin xyz="0.0 0.0 0.0" />
        <inertia ixx="0.0" ixy="-0.0" ixz="0.0"
                 iyy="0.0" iyz="-0.0"
                 izz="0.0" />
      </inertial-->
    </link>
    
    <xacro:logitech_c930e_camera name="camera" parent="camera_mount_link">
      <origin xyz="0.016 0.0 -0.0015" rpy="0.0 0.0 0.0" />
    </xacro:logitech_c930e_camera>
    
    <!-- add optional arm -->
    <xacro:if value="$(arg with_arm)">
      <xacro:include filename="$(find tuda_turtlebot3_arm_description)/urdf/tuda_turtlebot3_arm.urdf.xacro" />

      <xacro:manipulator_arm_macro parent="base_link">
        <origin xyz="0.136 0.0 0.0463" rpy="0.0 0.0 0.0" />
      </xacro:manipulator_arm_macro>
    </xacro:if>
  </xacro:macro>
</robot>
